### ISSUE TITLE
inference on single image?

### ISSUE THREAD

**Issue by ydzhang12345** [zhangfuyang/search_evaluate#1]
Hi,

Thank you for your great work! May I know how I could test the model on my own image? Many Thnx!

**Comment by zhangfuyang** [comment]
Hi,

This work is a refinement model, meaning that you can't use this from scratch. Ideally, you should already have an initial result of your own image. Then our model can improve the result by using classification & exploration techniques. In the worst case, you can run the model with only predicted corners (a really bad initial graph that w/o any edge).

May I know what kind of image you want to test? Is that also a building image similar to the image in the paper? or other kinds of structured data? If so, there may need some adjustments for the heuristic action set.

**Comment by ydzhang12345** [comment]
Hi,

Thanks for your reply. Yes, basically my data is satellite/RS image of city, and I would like to detect the building footprint in it.

**Comment by zhangfuyang** [comment]
Got it. I suggest you take a look at this [paper](https://arxiv.org/abs/2004.14875) if you only consider the boundary of the building. 

If you also want to reconstruct the inner edge of each building (more complex topology), you may want to look at our previous paper [Conv-MPN](https://arxiv.org/abs/1912.01756).

Whenever you have an initial result. You can probably use the idea of this work to further refine it :)

**Comment by ydzhang12345** [comment]
thnx!
